import { build } from 'esbuild';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { cpSync, readFileSync, writeFileSync } from 'node:fs';

const root = fileURLToPath(new URL('../', import.meta.url));
const panel = resolve(root, 'src/content/panel.ts');
// Inline a symbol so the mark renders even when the demo is opened as a local file.
const logo = readFileSync(resolve(root, 'public/branding/logo.svg'), 'utf8');
const paths = logo.slice(logo.indexOf('>') + 1, logo.lastIndexOf('</svg>')).trim();
const pagePath = resolve(root, 'landing/index.html');
const page = readFileSync(pagePath, 'utf8');
const marker = /<!-- chat-cleanup-logo:start -->[\s\S]*?<!-- chat-cleanup-logo:end -->/;
if (!marker.test(page)) throw new Error('Landing logo marker is missing');
writeFileSync(pagePath, page.replace(marker,
  `<!-- chat-cleanup-logo:start -->\n    <symbol id="chat-cleanup-logo" viewBox="0 0 128 128">${paths}</symbol>\n    <!-- chat-cleanup-logo:end -->`));
const result = await build({
  absWorkingDir: root,
  entryPoints: ['landing/main.ts'],
  bundle: true,
  format: 'iife',
  target: 'chrome120',
  write: false,
  banner: { js: '// Generated by npm run build:landing. Edit landing/*.ts or the shared extension UI.' },
  plugins: [{
    name: 'fictional-chatgpt-environment',
    setup(builder) {
      builder.onResolve({ filter: /(?:api|dom|local)\.ts$/ }, (args) => {
        const target = resolve(args.resolveDir, args.path);
        // Use the exact production UI, selection, protection, queue and recovery modules.
        // Substitute only the platform boundaries in this separately built demo.
        if (args.importer === panel && (
          target === resolve(root, 'src/chatgpt/api.ts') ||
          target === resolve(root, 'src/chatgpt/dom.ts')
        )) return { path: resolve(root, 'landing/environment.ts') };
        if (target === resolve(root, 'src/storage/local.ts')) {
          return { path: resolve(root, 'landing/storage.ts') };
        }
      });
    },
  }],
});
const code = result.outputFiles[0].text;
// Queue error types may be shared with api.ts; live request code must be tree-shaken away.
if (/\bfetch\s*\(|\/backend-api\/|\/api\/auth\/session|chrome\.storage/.test(code)) {
  throw new Error('Landing build contains a live platform boundary');
}
writeFileSync(resolve(root, 'landing/demo.js'), code);
cpSync(resolve(root, 'public/icons'), resolve(root, 'landing/icons'), { recursive: true });
cpSync(resolve(root, 'public/branding'), resolve(root, 'landing/branding'), { recursive: true });
console.log(`Landing built with shared product UI (${Math.round(code.length / 1024)} KiB).`);
